### ISSUE TITLE
Allowing dangerous operation: file operation

### ISSUE THREAD

**Issue by zsyh** [ggaaooppeenngg/libsandbox#6]
```
#include<stdio.h>
int main(){
  printf("hello world!");
  FILE * fp;
  fp = fopen("/home/zaizai/haha.txt","wb+");
  char buf[8191]={0};
  int fwritereturn;
  int freadreturn = sprintf(buf,"this is a file!");
  fwritereturn=fwrite(buf,1,freadreturn,fp);
  fclose(fp);
  return 0;
}
```
Creating a new file is possible by c code using your sandbox.  It's dangerous to server.

**Comment by ggaaooppeenngg** [comment]
@zsyh Hi, this is really a serious issue, libsandbox is just a toy, not maintained, I am not working on it now, this libsandbox is not best solution I think, if you want to block read or write system call, you can use [seccomp](https://blog.yadutaf.fr/2014/05/29/introduction-to-seccomp-bpf-linux-syscall-filter/) or use [selinux](https://wiki.centos.org/es/HowTos/SELinux) to control access, but libsandbox is unfortunately not going to be maintained.
